name: 'Label PR on Merge Bot'
description: 'Label pull requests with custom label on merge'
inputs:
  label:
    description: 'Label for the bot to trigger'
    required: false
    default: 'label on merge'
  post_merged_label:
    description: 'Label for the PR after it is merged'
    required: false
    default: 'merged'
  GITHUB_TOKEN:
    description: 'Authorization Token for accessing GitHub'
    required: true
runs:
  using: 'node12'
  main: 'source/index.js'
